/* Clicker PLH v1.0.0 — jogo offline sem dependências */
(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], SAVE='clickerPLH_save_v1', PRESTIGE_AT=1e8;
const generators=[
 ['auto','Auto Clicker',15,.2,1.15],['cursor','Cursor Neon',100,1,1.15],['machine','Máquina PLH',1100,8,1.16],['factory','Fábrica',13000,55,1.16],['server','Servidor Quântico',160000,360,1.17],['super','Supercomputador',2.2e6,2400,1.17],['lab','Laboratório',3.5e7,16000,1.18],['reactor','Reator Estelar',6e8,120000,1.18],['portal','Portal',1.1e10,9e5,1.19],['dimension','Dimensão PLH',2.5e11,8e6,1.2]
].map(([id,name,cost,prod,growth])=>({id,name,cost,prod,growth}));
const upgrades=[
 ['tap1','Clique Reforçado','Poder de clique +1',10,()=>S.clickFlat+=1],['tap2','Clique Duplo','Poder de clique +2',75,()=>S.clickFlat+=2],['tap3','Luvas Neon','Poder de clique +5',500,()=>S.clickFlat+=5],['tap4','Impacto PLH','Poder de clique ×2',4000,()=>S.clickMult*=2],['auto1','Óleo de Máquina','Produção automática ×2',12000,()=>S.autoMult*=2],['crit1','Olho Crítico','Chance crítica +5%',25000,()=>S.critChance+=.05],['tap5','Clique Quântico','Poder de clique ×3',80000,()=>S.clickMult*=3],['crit2','Crítico Pesado','Força crítica +2×',250000,()=>S.critMult+=2],['global1','Sinergia','Toda produção ×2',1e6,()=>S.globalMult*=2],['auto2','Overclock','Produção automática ×3',8e6,()=>S.autoMult*=3],['tap6','Mãos Dimensionais','Poder de clique ×5',5e7,()=>S.clickMult*=5],['global2','Singularidade','Toda produção ×5',7e8,()=>S.globalMult*=5]
].map(([id,name,desc,cost,buy])=>({id,name,desc,cost,buy}));
const specials=[
 ['s1','Ritmo Crescente','Combo 50% mais forte',1000,'total',1000,()=>S.comboPower*=1.5],['s2','Engrenagens Gêmeas','Auto Clickers e Cursores ×3',5e4,'gens',25,()=>S.specialGen*=3],['s3','Sorte PLH','Chance crítica +8%',1e5,'crits',25,()=>S.critChance+=.08],['s4','Mestre do Toque','Cliques ×3',1e6,'clicks',1000,()=>S.clickMult*=3],['s5','Automação Suprema','Produção automática ×4',2e7,'total',1e7,()=>S.autoMult*=4]
].map(([id,name,desc,cost,req,val,buy])=>({id,name,desc,cost,req,val,buy}));
const achievements=[['a1','Primeiro passo','Faça 1 clique','clicks',1],['a2','Dedo quente','Faça 100 cliques','clicks',100],['a3','Incansável','Faça 2.000 cliques','clicks',2000],['a4','Poupador','Tenha 10K moedas','coins',1e4],['a5','Magnata','Produza 1M moedas','total',1e6],['a6','Império','Produza 1B moedas','total',1e9],['a7','Automação','Tenha 10 geradores','gens',10],['a8','Exército mecânico','Tenha 100 geradores','gens',100],['a9','Que sorte!','Faça 10 críticos','crits',10],['a10','Crítico mestre','Faça 500 críticos','crits',500],['a11','No ritmo','Alcance combo 30','combo',30],['a12','Colecionador','Compre 8 upgrades','ups',8],['a13','Renascido','Faça um Prestige','prestiges',1]].map(x=>({id:x[0],name:x[1],desc:x[2],stat:x[3],goal:x[4]}));
const missionDefs=[['clicks','Clique {n} vezes',100,2.2],['gens','Compre {n} geradores',10,1.9],['crits','Faça {n} críticos',10,2],['total','Produza {n} moedas',5000,8],['combo','Alcance combo {n}',20,1.7]];
const permanent=[['pglobal','Núcleo Eterno','Produção global +25% por nível',1.8],['pclick','Mãos de Cristal','Clique +50% por nível',2],['pauto','Motores Eternos','Automação +35% por nível',1.9],['pcrit','Prisma da Sorte','Chance crítica +1% por nível',2.1],['pdiscount','Mercador Cósmico','Preços de geradores -2% por nível',2.2]];
const base=()=>({coins:0,total:0,manual:0,automatic:0,clicks:0,crits:0,bestCombo:0,combo:0,lastClick:0,clickFlat:1,clickMult:1,autoMult:1,globalMult:1,critChance:.03,critMult:2,comboPower:1,specialGen:1,gens:{},bought:[],specials:[],achievements:[],upgradesBought:0,gensBought:0,prestiges:0,crystals:0,permanent:{},buffs:[],missions:[],missionLevel:0,playTime:0,lastSave:Date.now(),settings:{volume:.25,particles:true,reducedMotion:false,notation:'short',confirmBuy:false},tutorial:false});
let S=base(), buyMode='1', last=performance.now(), displayed=0, audio=null, modalCallback=null;
const finite=(n,max=1e300)=>Number.isFinite(+n)?Math.max(0,Math.min(max,+n)):0;
function hydrate(raw){const b=base();S={...b,...raw,settings:{...b.settings,...raw.settings},gens:{...raw.gens},permanent:{...raw.permanent}};['coins','total','manual','automatic','clicks','crits','bestCombo','playTime','crystals'].forEach(k=>S[k]=finite(S[k]));generators.forEach(g=>S.gens[g.id]=Math.floor(finite(S.gens[g.id])));}
function fmt(n){n=finite(n);if(S.settings.notation==='scientific'&&n>=1e4)return n.toExponential(2);if(n<1000)return n<10?n.toFixed(2).replace(/\.00$/,''):Math.floor(n).toLocaleString('pt-BR');const suf=['K','M','B','T','Qa','Qi','Sx','Sp','Oc','No','Dc','Ud','Dd','Td','Qad','Qid','Sxd','Spd','Ocd','Nod','Vg'];let i=Math.min(Math.floor(Math.log10(n)/3),suf.length);return i>=suf.length?n.toExponential(2):(n/10**(i*3)).toFixed(n/10**(i*3)<10?2:1).replace(/\.0+$/,'')+suf[i-1]}
const perm=(id)=>S.permanent[id]||0, achievementBonus=()=>1+S.achievements.length*.01;
function clickPower(){return S.clickFlat*S.clickMult*(1+perm('pclick')*.5)*S.globalMult*(1+perm('pglobal')*.25)*achievementBonus()*(buff('click')||1)}
function cps(){let sum=generators.reduce((a,g)=>a+(S.gens[g.id]||0)*g.prod*((g.id==='auto'||g.id==='cursor')?S.specialGen:1),0);return sum*S.autoMult*(1+perm('pauto')*.35)*S.globalMult*(1+perm('pglobal')*.25)*achievementBonus()*(buff('production')||1)}
function buff(type){const now=Date.now(), b=S.buffs.filter(x=>x.until>now&&x.type===type);return b.reduce((v,x)=>v*x.mult,1)}
function addCoins(n,kind){n=finite(n);S.coins=finite(S.coins+n);S.total=finite(S.total+n);S[kind]=finite(S[kind]+n)}
function genCost(g,start,count){const discount=Math.max(.7,1-perm('pdiscount')*.02),a=g.cost*discount*g.growth**start;return a*(g.growth**count-1)/(g.growth-1)}
function amountFor(g){const owned=S.gens[g.id]||0;if(buyMode!=='MAX')return +buyMode;let lo=0,hi=1;while(hi<1e6&&genCost(g,owned,hi)<=S.coins)hi*=2;while(lo+1<hi){let m=Math.floor((lo+hi)/2);genCost(g,owned,m)<=S.coins?lo=m:hi=m}return lo}
function unlockedGen(i){return i===0||S.total>=generators[i].cost/3}
function reqValue(type){return type==='gens'?S.gensBought:type==='ups'?S.upgradesBought:type==='combo'?S.bestCombo:type==='prestiges'?S.prestiges:S[type]||0}
function save(){S.lastSave=Date.now();try{localStorage.setItem(SAVE,JSON.stringify(S))}catch(e){toast('Não foi possível salvar neste navegador.')}}
function load(){try{const raw=localStorage.getItem(SAVE);if(raw)hydrate(JSON.parse(raw))}catch(e){hydrate({});toast('Save inválido: um novo jogo foi iniciado.')}const away=Math.min(8*3600,Math.max(0,(Date.now()-S.lastSave)/1000));if(away>60&&cps()>0){const gain=cps()*away*.5;addCoins(gain,'automatic');showModal('Progresso offline',`Você ficou fora por ${duration(away)} e ganhou ${fmt(gain)} moedas (50% da produção, limite de 8h).`,null,false)}S.lastSave=Date.now();if(!S.missions.length)newMissions();}
function duration(sec){sec=Math.floor(sec);const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return [h&&h+'h',m&&m+'min',!h&&s+'s'].filter(Boolean).join(' ')}
function doClick(e){const now=Date.now(),delta=now-S.lastClick;if(delta<90)return;S.combo=delta<900?Math.min(100,S.combo+1):1;S.lastClick=now;S.clicks++;S.bestCombo=Math.max(S.bestCombo,S.combo);const combo=1+Math.min(1,S.combo*.01*S.comboPower),crit=Math.random()<Math.min(.75,S.critChance+perm('pcrit')*.01+(buff('crit')-1));const gain=clickPower()*combo*(crit?S.critMult:1);if(crit)S.crits++;addCoins(gain,'manual');visualClick(e,gain,crit);sound(crit?'crit':'click');checkAll();}
function visualClick(e,gain,crit){const zone=$('#clickZone'),r=zone.getBoundingClientRect(),x=e?.clientX?e.clientX-r.left:r.width/2,y=e?.clientY?e.clientY-r.top:r.height/2;const f=document.createElement('b');f.className='float '+(crit?'crit':'');f.textContent=(crit?'CRÍTICO! ':'')+'+'+fmt(gain);f.style.cssText=`left:${x}px;top:${y}px;--dx:${(Math.random()-.5)*50}px`;zone.append(f);setTimeout(()=>f.remove(),900);if(S.settings.particles&&!S.settings.reducedMotion)for(let i=0;i<7;i++){const p=document.createElement('i');p.className='particle';p.style.cssText=`left:${x}px;top:${y}px;--x:${(Math.random()-.5)*110}px;--y:${(Math.random()-.5)*110}px`;zone.append(p);setTimeout(()=>p.remove(),650)}const b=$('#clickButton');b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),70)}
function sound(type){if(!S.settings.volume)return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),freq={click:220,buy:420,crit:720,achievement:880,prestige:160}[type]||300;o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(Math.min(.08,S.settings.volume*.08),audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.08);o.start();o.stop(audio.currentTime+.08)}catch(e){}}
function buyUpgrade(u){if(S.bought.includes(u.id)||S.coins<u.cost)return;S.coins-=u.cost;S.bought.push(u.id);S.upgradesBought++;u.buy();sound('buy');checkAll();save();renderStore()}
function buyGen(g){const n=amountFor(g);if(n<1)return;const cost=genCost(g,S.gens[g.id],n);if(cost>S.coins*1.0000001)return;S.coins=Math.max(0,S.coins-cost);S.gens[g.id]+=n;S.gensBought+=n;sound('buy');checkAll();save();renderStore()}
function buySpecial(s){if(S.specials.includes(s.id)||reqValue(s.req)<s.val||S.coins<s.cost)return;const go=()=>{S.coins-=s.cost;S.specials.push(s.id);s.buy();sound('buy');save();renderSpecials()};S.settings.confirmBuy?showModal('Confirmar melhoria',`Comprar ${s.name} por ${fmt(s.cost)}?`,go):go()}
function checkAll(){achievements.forEach(a=>{if(!S.achievements.includes(a.id)&&reqValue(a.stat)>=a.goal){S.achievements.push(a.id);toast(`🏆 Conquista: ${a.name}`);sound('achievement')}});S.missions.forEach(m=>{if(!m.done&&reqValue(m.type)-m.start>=m.target)m.done=true});}
function newMissions(){S.missions=missionDefs.slice(0,3).map((d,i)=>{const level=S.missionLevel+i,target=Math.ceil(d[2]*d[3]**Math.floor(level/3));return{id:d[0]+level,type:d[0],title:d[1].replace('{n}',fmt(target)),target,start:reqValue(d[0]),reward:Math.max(100,target*(d[0]==='total'?.15:clickPower()*2)),done:false}})}
function claimMission(m){if(!m.done)return;addCoins(m.reward,'manual');toast(`Missão concluída: +${fmt(m.reward)}`);S.missionLevel++;S.missions=S.missions.filter(x=>x.id!==m.id);const d=missionDefs[S.missionLevel%missionDefs.length],target=Math.ceil(d[2]*d[3]**Math.floor(S.missionLevel/3));S.missions.push({id:d[0]+S.missionLevel,type:d[0],title:d[1].replace('{n}',fmt(target)),target,start:reqValue(d[0]),reward:Math.max(100,target*(d[0]==='total'?.15:clickPower()*2)),done:false});save();renderMissions()}
function prestigeGain(){return Math.floor(Math.sqrt(S.total/PRESTIGE_AT))}
function doPrestige(){const gain=prestigeGain();if(gain<1)return;showModal('Confirmar Prestige',`Você reiniciará moedas, geradores e melhorias desta partida em troca de ${gain} cristais. Esta ação não pode ser desfeita.`,()=>{const keep={crystals:S.crystals+gain,permanent:S.permanent,prestiges:S.prestiges+1,achievements:S.achievements,settings:S.settings,tutorial:true,playTime:S.playTime};hydrate({...keep});newMissions();save();renderAll();toast(`💎 Prestige realizado: +${gain} cristais`);sound('prestige')})}
function buyPermanent(p){const level=perm(p[0]),cost=Math.ceil(p[3]**level);if(S.crystals<cost)return;S.crystals-=cost;S.permanent[p[0]]=level+1;save();renderPermanent()}
function goldenEvent(){if(!$('#golden').hidden)return;const b=$('#golden'),zone=$('#clickZone');b.hidden=false;b.style.left=10+Math.random()*75+'%';b.style.top=12+Math.random()*65+'%';b._timer=setTimeout(()=>b.hidden=true,7000)}
function claimGolden(){const rolls=['production','click','crit'],type=rolls[Math.floor(Math.random()*rolls.length)],data={production:[2,30,'Produção ×2'],click:[5,15,'Clique ×5'],crit:[1.25,20,'Crítico aumentado']}[type];S.buffs.push({type,mult:data[0],until:Date.now()+data[1]*1000,name:data[2]});$('#golden').hidden=true;clearTimeout($('#golden')._timer);toast(`✦ ${data[2]} por ${data[1]}s!`);save()}
function toast(text){const d=document.createElement('div');d.className='toast';d.textContent=text;$('#toasts').append(d);setTimeout(()=>d.remove(),4100)}
function showModal(title,text,cb,input=false){modalCallback=cb;$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modalInput').hidden=!input;$('#modalInput').value='';$('#modal').hidden=false;$('#modalCancel').hidden=!cb&&!input;$('#modalOk').textContent=input?'Importar':'Confirmar'}
function renderStore(){const up=$('#upgrades');up.innerHTML=upgrades.map(u=>{const bought=S.bought.includes(u.id);return `<article class="card ${S.coins>=u.cost?'affordable':''} ${bought?'locked':''}"><div><h3>${u.name}</h3><p>${u.desc}</p><span class="price">${bought?'Comprado':fmt(u.cost)+' moedas'}</span></div><button data-up="${u.id}" ${bought||S.coins<u.cost?'disabled':''}>${bought?'✓':'Comprar'}</button></article>`}).join('');const visible=generators.filter((g,i)=>unlockedGen(i));$('#generators').innerHTML=visible.map(g=>{const n=amountFor(g),cost=n?genCost(g,S.gens[g.id],n):genCost(g,S.gens[g.id],1),total=S.gens[g.id]*g.prod*S.autoMult;return `<article class="card ${n&&S.coins>=cost?'affordable':''}"><div><h3>${g.name} <small>×${S.gens[g.id]}</small></h3><p>${fmt(g.prod)}/s cada · ${fmt(total)}/s total</p><span class="price">${n?fmt(cost):'Sem recursos'} ${n?'· x'+n:''}</span></div><button data-gen="${g.id}" ${!n||S.coins<cost?'disabled':''}>Comprar</button></article>`}).join('');$('#shopBadge').hidden=!upgrades.some(u=>!S.bought.includes(u.id)&&S.coins>=u.cost)}
function renderSpecials(){$('#specials').innerHTML=specials.map(s=>{const got=S.specials.includes(s.id),open=reqValue(s.req)>=s.val;return `<article class="card ${got?'locked':''} ${open&&S.coins>=s.cost?'affordable':''}"><div><h3>${open?s.name:'???'}</h3><p>${open?s.desc:`Requer ${fmt(s.val)} em ${s.req}`}</p><span class="price">${got?'Obtido':fmt(s.cost)+' moedas'}</span></div><button data-special="${s.id}" ${got||!open||S.coins<s.cost?'disabled':''}>${got?'✓':'Desbloquear'}</button></article>`}).join('')}
function renderMissions(){$('#missionList').innerHTML=S.missions.map(m=>{const v=Math.max(0,reqValue(m.type)-m.start),pct=Math.min(100,v/m.target*100);return `<article class="card ${m.done?'affordable':''}"><div><h3>${m.title}</h3><p>${fmt(Math.min(v,m.target))} / ${fmt(m.target)}</p><span class="price">Recompensa: ${fmt(m.reward)}</span></div><button data-mission="${m.id}" ${!m.done?'disabled':''}>Resgatar</button><div class="progress bar"><i style="width:${pct}%"></i></div></article>`}).join('')}
function renderAchievements(){$('#achievementSummary').textContent=`${S.achievements.length}/${achievements.length} desbloqueadas · bônus global +${S.achievements.length}%`;$('#achievementList').innerHTML=achievements.map(a=>{const got=S.achievements.includes(a.id);return `<article class="card ${got?'unlocked':'locked'}"><span class="achievement-icon">${got?'🏆':'🔒'}</span><div><h3>${got?a.name:'Conquista oculta'}</h3><p>${got?a.desc:'Continue jogando para descobrir.'}</p></div></article>`}).join('')}
function renderPermanent(){$('#permanents').innerHTML=permanent.map(p=>{const l=perm(p[0]),cost=Math.ceil(p[3]**l);return `<article class="card ${S.crystals>=cost?'affordable':''}"><div><h3>${p[1]} <small>Nv. ${l}</small></h3><p>${p[2]}</p><span class="price">${cost} 💎</span></div><button data-perm="${p[0]}" ${S.crystals<cost?'disabled':''}>Melhorar</button></article>`}).join('')}
function renderStats(){const stats=[['Tempo jogado',duration(S.playTime)],['Cliques',fmt(S.clicks)],['Críticos',fmt(S.crits)],['Maior combo',fmt(S.bestCombo)],['Moedas atuais',fmt(S.coins)],['Produção total',fmt(S.total)],['Produção manual',fmt(S.manual)],['Produção automática',fmt(S.automatic)],['Upgrades comprados',fmt(S.upgradesBought)],['Geradores comprados',fmt(S.gensBought)],['Prestiges',fmt(S.prestiges)],['Cristais obtidos',fmt(S.crystals+Object.entries(S.permanent).reduce((a,[id,l])=>{const p=permanent.find(x=>x[0]===id);let c=0;for(let i=0;i<l;i++)c+=Math.ceil(p[3]**i);return a+c},0))]];$('#statsList').innerHTML=stats.map(x=>`<div>${x[0]}<b>${x[1]}</b></div>`).join('')}
function unlockInfo(){const list=[[1000,'Upgrades especiais'],[5000,'Sistema de críticos'],[25000,'Missões'],[1e5,'Conquistas'],[PRESTIGE_AT,'Prestige']];const next=list.find(x=>S.total<x[0]);if(!next)return['Todos os sistemas foram revelados!',100];return[`${next[1]} em ${fmt(next[0])} moedas totais`,Math.min(100,S.total/next[0]*100)]}
function renderHUD(){displayed+=(S.coins-displayed)*.2;if(Math.abs(displayed-S.coins)<.01)displayed=S.coins;$('#coins').textContent=fmt(displayed);$('#cps').textContent=fmt(cps());$('#clickPower').textContent=fmt(clickPower());$('#crystals').textContent=fmt(S.crystals);$('#manualTotal').textContent=fmt(S.manual);$('#autoTotal').textContent=fmt(S.automatic);$('#critInfo').textContent=`${Math.round(Math.min(.75,S.critChance+perm('pcrit')*.01)*100)}% ×${fmt(S.critMult)}`;const combo=1+Math.min(1,S.combo*.01*S.comboPower);$('#combo b').textContent='x'+combo.toFixed(2).replace('.',',');$('#combo span').textContent=S.combo;$('#combo').classList.toggle('hot',S.combo>=30);const [txt,pct]=unlockInfo();$('#nextUnlock').textContent=txt;$('#unlockBar').style.width=pct+'%';$('#clickButton').className=S.total>=1e7?'level3':S.total>=1e4?'level2':'';const now=Date.now();S.buffs=S.buffs.filter(b=>b.until>now);$('#buffs').innerHTML='<h3>Bônus ativos</h3>'+(S.buffs.length?S.buffs.map(b=>`<div>${b.name} — ${Math.ceil((b.until-now)/1000)}s<i style="width:${Math.min(100,(b.until-now)/300)}%"></i></div>`).join(''):'<p class="muted">Nenhum bônus ativo.</p>');const unlock={special:S.total>=1000,missions:S.total>=25000,achievements:S.total>=1e5,prestige:S.total>=PRESTIGE_AT||S.prestiges>0};$$('[data-unlock]').forEach(b=>b.hidden=!unlock[b.dataset.unlock]);$('#prestigeGain').textContent=prestigeGain();$('#prestigeButton').disabled=prestigeGain()<1}
function renderAll(){renderHUD();renderStore();renderSpecials();renderMissions();renderAchievements();renderPermanent();renderStats();applySettings()}
function applySettings(){$('#volume').value=S.settings.volume;$('#particles').checked=S.settings.particles;$('#reducedMotion').checked=S.settings.reducedMotion;$('#notation').value=S.settings.notation;$('#confirmBuy').checked=S.settings.confirmBuy;document.body.classList.toggle('reduce-motion',S.settings.reducedMotion)}
function loop(now){const dt=Math.min(.25,(now-last)/1000);last=now;S.playTime+=dt;const income=cps()*dt;if(income)addCoins(income,'automatic');if(Date.now()-S.lastClick>1200)S.combo=Math.max(0,S.combo-dt*8);renderHUD();requestAnimationFrame(loop)}
function bind(){$('#clickButton').addEventListener('pointerdown',doClick);document.addEventListener('keydown',e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();if(!e.repeat)doClick()}});$('#golden').onclick=claimGolden;$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;$$('#tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='stats')renderStats()};$('#buyModes').onclick=e=>{if(e.target.tagName!=='BUTTON')return;buyMode=e.target.textContent;$$('#buyModes button').forEach(b=>b.classList.toggle('active',b===e.target));renderStore()};document.addEventListener('click',e=>{let b=e.target.closest('[data-up],[data-gen],[data-special],[data-mission],[data-perm]');if(!b)return;if(b.dataset.up)buyUpgrade(upgrades.find(x=>x.id===b.dataset.up));if(b.dataset.gen)buyGen(generators.find(x=>x.id===b.dataset.gen));if(b.dataset.special)buySpecial(specials.find(x=>x.id===b.dataset.special));if(b.dataset.mission)claimMission(S.missions.find(x=>x.id===b.dataset.mission));if(b.dataset.perm)buyPermanent(permanent.find(x=>x[0]===b.dataset.perm))});$('#prestigeButton').onclick=doPrestige;['volume','particles','reducedMotion','notation','confirmBuy'].forEach(id=>$('#'+id).addEventListener('change',e=>{S.settings[id]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?+e.target.value:e.target.value;applySettings();save()}));$('#exportSave').onclick=()=>showModal('Exportar save','Copie e guarde este texto:',null,true),$('#exportSave').addEventListener('click',()=>setTimeout(()=>{$('#modalInput').value=btoa(unescape(encodeURIComponent(JSON.stringify(S))));$('#modalInput').select()},0));$('#importSave').onclick=()=>showModal('Importar save','Cole abaixo o save exportado:',()=>{try{hydrate(JSON.parse(decodeURIComponent(escape(atob($('#modalInput').value.trim())))));save();renderAll();toast('Save importado com sucesso!')}catch(e){toast('Texto de save inválido.')}},true);$('#wipeSave').onclick=()=>{const answer=prompt('Para apagar TODO o progresso, digite APAGAR:');if(answer==='APAGAR')showModal('Última confirmação','Todo o progresso será perdido permanentemente.',()=>{localStorage.removeItem(SAVE);location.reload()})};$('#modalCancel').onclick=()=>$('#modal').hidden=true;$('#modalOk').onclick=()=>{const cb=modalCallback;$('#modal').hidden=true;modalCallback=null;if(cb)cb()};$('#tutorialOk').onclick=()=>{$('#tutorial').hidden=true;S.tutorial=true;save()};window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()})}
load();bind();renderAll();displayed=S.coins;if(!S.tutorial)$('#tutorial').hidden=false;setInterval(save,15000);setInterval(()=>{renderStore();renderSpecials();renderMissions();checkAll()},1000);setInterval(()=>{if(Math.random()<.35)goldenEvent()},30000);requestAnimationFrame(loop);
})();
